spring:
  application:
    name: aviation-routes-service
  datasource:
    url: jdbc:postgresql://db-ip:5432/AVIATIONDB
    username: db-user  # TODO: Store in a secure place as encrypted
    password: db-pass # TODO: Store in a secure place as encrypted
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 3434
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: never
logging:
  level:
    "[org.springframework]": ERROR
    "[com.example.aviation]": DEBUG
springdoc:
  api-docs:
    version: OPENAPI_3_0
    enabled: true